# Generated by Django 3.0.4 on 2020-03-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SOME STRING', max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('video', models.FileField(default='default.jpg', upload_to='videos')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
