# Generated by Django 3.0.4 on 2020-03-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20200313_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
